REM INSERTING into SYSTEM.USER_DETAILS
SET DEFINE OFF;
Insert into SYSTEM.USER_DETAILS (ID,NAME,TYPE) values ('101','Ram','admin');
Insert into SYSTEM.USER_DETAILS (ID,NAME,TYPE) values ('102','Nitin','user');